version: '2.1'
services:

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql/
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - db.env

  redis:
    image: redis
    restart: always

  app:
    build: ./app
    restart: always
    volumes:
      - friendica:/var/www/html
    environment:
      - FRIENDICA_ADMIN_MAIL=
      - FRIENDICA_TZ=
      - FRIENDICA_LANG=
      - SITENAME=
      - SMTP=
    env_file:
      - db.env
    depends_on:
      - db
    hostname: friendica.local
    ports:
      - "80:80"

  cron:
    build: ./app
    restart: always
    volumes:
      - friendica:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
    hostname: friendica.local

volumes:
  db:
  friendica: